### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by dominionish** [jimsch/CoAP-CSharp#10]
Good day!
I have a build problem with this repository.
VS2015 cannot build constructions like:
get => _exchange:
public Exchange Exchange
        {
            get => _exchange;
        }
and

_config = config?? throw ThrowHelper.ArgumentNull("config");

How do you build this code? Should I install any extention for VS?

![image](https://cloud.githubusercontent.com/assets/8955774/26525478/8014549c-4371-11e7-8cb0-9b70bb5725e4.png)

**Comment by jimsch** [comment]
I am building using VS 2017.  This also builds using the latest mono build version as well.  Do you have a switch on which version of C# can be used?

**Comment by dominionish** [comment]
Yes I have switch on which version of C# can be used. Now I use C# version 5.0. I quess i need 6.0, am I right?

**Comment by dominionish** [comment]
I got it. We need to use C# version 7.0.
Thank you!
