### ISSUE TITLE
Build project in VS2015

### ISSUE THREAD

**Issue by dominionish** [jimsch/CoAP-CSharp#16]
Hello!
I use VS2015 and you code dont build. But there is a solution - to build you code I should install nuget packages:
System.ValueTuple
Microsoft.Net.Compilers
So you can install it in all Coap.Net projects (in CoAP.NET folder) and push new package.json , so everyone will not have problem with building and all will work from the box.
It is just suggestion.

**Comment by jimsch** [comment]
I am sorry, however I am using language features from the version 17 compiler - this requires the use of VS2017 as near as I can tell-- see issue #10

**Comment by jimsch** [comment]
Wait - just to be sure - are you saying you cannot compile w/ the library as a nuget or the raw source - I am assuming you mean raw source.

**Comment by dominionish** [comment]
Yes, you right - raw source
