### ISSUE TITLE
"Don't send because the sessions are different"

### ISSUE THREAD

**Issue by Moskus** [jimsch/CoAP-CSharp#17]
I don't know what this means but if I turn of the insane logging to the console, this message shows up instead. Started wih .13 I believe.

**Comment by jimsch** [comment]
Ignore this for now, it is part of some code that I am still trying to get correct.

**Comment by Moskus** [comment]
I figured. :)
It's just that is's creating alot of logging in the host application (I'm creating plugin). Not a giant problem, just annoying.

**Comment by jimsch** [comment]
Should be fixed in the 1.1.5 drop
