### ISSUE TITLE
"Observe" mode

### ISSUE THREAD

**Issue by Hydro8** [jimsch/CoAP-CSharp#25]
Hi
A friend use the libcoap library to control Ikea Tradfri. He explains to me that there is an option in libcoap to "observe" a device and to receive event, the connexion isn't kill after the first message.

Is it possible to do something like this with your library ? Appartently the coap command looks like 
`coaps://host:port/id`

Sorry if you answer that before or if I don't explain well.

**Comment by jimsch** [comment]
Yes there are several ways to do this depending on how you want to get the  responses.

CoapClient.Observe is the method you are looking for.

**Comment by Hydro8** [comment]
Basically I want to listen to bulb / group change but I don't find many documentation for this.
Do you have test this ?

**Comment by jimsch** [comment]
I am playing with an example now.

**Comment by Hydro8** [comment]
Ok thank a lot !

**Comment by Hydro8** [comment]
Do you have any update on this ?

**Comment by jimsch** [comment]
It is in the wiki

**Comment by Hydro8** [comment]
Sorry I didn't see it, thank for your help !
However as usual I've got problems.

Here my code

`     OneKey userKey = new OneKey();    
     userKey.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);      
    userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes("my_key")));
            CoAPEndPoint ep = new DTLSClientEndPoint(userKey);
            CoapClient client = new CoapClient(new Uri("coaps://192.168.1.128:5684/resource"))
            {
                EndPoint = ep
            };
            ep.Start();
            client.Observe(NotifyEvent, FailEvent);`

I don't have anything. If I remove

`            {
                EndPoint = ep
            };
            ep.Start();`

It says 

> Critical Error : System.Exception: Schema is incorrect for the end point
   à Com.AugustCellars.CoAP.Net.CoAPEndPoint.SendRequest(Request request) dans C:\Projects\coap\CoAP-CSharp\CoAP-CSharp\CoAP.NET\Net\CoAPEndPoint.cs:ligne 247
   à Com.AugustCellars.CoAP.Request.Send() dans C:\Projects\coap\CoAP-CSharp\CoAP-CSharp\CoAP.NET\Request.cs:ligne 241
   à Com.AugustCellars.CoAP.CoapClient.ObserveAsync(Request request, Action`1 notify, Action`1 error) dans C:\Projects\coap\CoAP-CSharp\CoAP-CSharp\CoAP.NET\CoapClient.cs:ligne 468
   à Com.AugustCellars.CoAP.CoapClient.Observe(Request request, Action`1 notify, Action`1 error) dans C:\Projects\coap\CoAP-CSharp\CoAP-CSharp\CoAP.NET\CoapClient.cs:ligne 432
   à Com.AugustCellars.CoAP.CoapClient.Observe(Action`1 notify, Action`1 error) dans C:\Projects\coap\CoAP-CSharp\CoAP-CSharp\CoAP.NET\CoapClient.cs:ligne 366
   à Trådfri.Program.OnStart() dans C:\Users\Alpha\Documents\Visual Studio 2017\Projects\Trådfri\Trådfri\Program.cs:ligne 36
   à Constellation.Package.PackageHost.Start(Type packageType, String constellationUri, String sentinelName, String packageName, String accessKey)

**Comment by jimsch** [comment]
That makes no sense that you are getting that failure.  A log from the library would be useful to figure out what happened.

Without those two lines, you are going to get nothing as there is no non-DTLS support by the device

**Comment by Hydro8** [comment]
It works with your code however after x minutes I didn't receive anything. Is it something related to reconnect option ?

**Comment by Hydro8** [comment]
Apparently, 1 minute after I started the connexion I didn't receive update.

**Comment by jimsch** [comment]
https://github.com/jimsch/CoAP-CSharp/wiki/Observe-Example - see notes section

**Comment by Hydro8** [comment]
Sorry it seems that I don't read the wiki entirely :/

I know how to create endpoint with the app that send the command with :
IPEndPoint local = (IPEndPoint)findList.Client.LocalEndPoint;

How do I tell Tradfri to reply to a specific port ?

**Comment by jimsch** [comment]
CoAPEndPoint ep = new DTLSClientEndPoint(userKey, 9999);

will use the specific port

**Comment by Hydro8** [comment]
Ok I add this port for testing and I has a windows pop-up to allow my application.
I allowed it but I still get no reponse after 62 secondes.

**Comment by jimsch** [comment]
62 seconds still sounds like it is a firewall problem of some type.  If you install and use wireshark to look for traffic related to coaps, it will show if there are observe notifications being sent after the 62 second boundary but that are not being delivered to your application.  If so this is definitely a firewall problem.

You should also verify that you are using the latest drop as it had a fix that will affect your observe sooner or later.

**Comment by Hydro8** [comment]
Ok I looked with wireshark, ip sender is the IP of my gateway. 
After I started my app, my gateway send data for 91 secondes. 
After this 91 secondes, nothing appear from this ip. 

I retried multiple times and each time it stops after 91 secondes. 

What did you mean by latest drop ? Last update of your library ?

**Comment by jimsch** [comment]
Yes - the last update of this library.   Looks like that is probably the bug that I fixed when I pushed it out.  However that does not answer the 62 vs 91 question.

**Comment by Hydro8** [comment]
Common I think I found the problem...
ep.stop() after all subscribe :/

Apparently it works fine, only one question remains, is it possible to get URI separately or must I use string.split ? 

For example, //15001/65537, is it possible to have 15001 in one variable and 65537 in another ?

**Comment by jimsch** [comment]
the field is can be any number of things where parsing into a set of strings would not be possible.  For example, this can be a full URL rather than a URL path which would be a set of strings

**Comment by Hydro8** [comment]
It's me...again
Your example works great but I don't achieve to do what I want.

Basically I want for a group A to subscribe to the first bulb only (I don't need x report for the same group).
But I don't find the group ID in bulb report.

`            foreach (var node in items)
            {
                client.UriPath = node.Uri;
                var explode = node.Uri.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
                if((explode[0] == "15004")&&(explode.Length > 1))
                {
                    if (int.TryParse(texplode[1], out result))
                    {
                        Groupir dict2 = new Groupir();
                        RootObject2 group = this.GroupState(Convert.ToInt32(explode[1]));
                        List<Bulbs> bulbs = new List<Bulbs>();
                        foreach(var member in group.test1.test2.test3)
                        {
                            Bulbs bulb = new Bulbs();
                            RootObject resultbulb = JsonConvert.DeserializeObject<RootObject>(CurrentState(member).ResponseText);
                            bulb.type = resultbulb.numbertype.type;
                            bulb.id = member;
                            bulb.name = resultbulb.name;
                            bulbs.Add(bulb);
                            if ((bulb.type != "TRADFRI wireless dimmer")&&(bulb.type != "TRADFRI remote control")){
                       CoapObserveRelation relation1 = client.Observe(r => { EventIn("//15001/" + member, r); });
                            //  }
                        }
                    }

                }
            }`

But the event isn't trigger. What the difference between "//15001/" + member and node.Uri ?

Is there a better way to get groups, get members of this group and observe the first bulb ?

Thank

**Comment by Hydro8** [comment]
Ok I miss something. You can control each bulb individually even if they are in a group. 
So I  create a dictionary with bulb id and the group id. When bulb report something, I add group id as informations. 

But my question is how to control a group ? When I control a bulb, it only change this bulb not all the group. I try 15004 with group id but it doesn't work. 

Is there a way to send a command to a group or must I loop through all bulb inside a group to send command ,?

**Comment by jimsch** [comment]
Sending it to the group should just work, but I am not going to be able to look at this until end of next week.

**Comment by Hydro8** [comment]
I'm sending to coaps://192.168.1.128:5684/15004/ + groupId but doesn't work.

Maybe the command doesn't look like this
string test3 = "{{\"3311\":[{{{\"5850\":1}}]}}";

**Comment by jimsch** [comment]
If I send the same command to the group that I send to the bulb it seems to work just fine.  I don't know what your problem here is.  The string you have above seems to not be what I would expect in terms of json.  I use "{ \"3311\":[{ \"5850\":0}]}" to turn the group off.  I would imagine that if you turn the group on and the bulb is turned off then it would not turn on the bulb but I have not checked that.

**Comment by Hydro8** [comment]
Did you send this command to the same URL as I wrote above ?

**Comment by Hydro8** [comment]
If I send  { "3311":[{ "5851":0}]} to coaps://192.168.1.128:5684/15004/136834 only one bulb turn off :(

**Comment by jimsch** [comment]
Now that I put in a second bulb, it appears that { \"5850\":1} works better

**Comment by Hydro8** [comment]
I try to send { "5850":1}  to my group but nothing happen, even if the group is turn on or off.

Did I miss something ?

**Comment by Hydro8** [comment]
Do you have informations how send to group work ?
