### ISSUE TITLE
PSK?

### ISSUE THREAD

**Issue by Moskus** [jimsch/CoAP-CSharp#3]
With Ikea Trådfri demanding the use of PSK, can someone point me in the right direction on how to use it with this project?

Thanks! :)

**Comment by jimsch** [comment]
I assume that this means you want DTLS - I am working on it but have not yet released it.

**Comment by Moskus** [comment]
That is great news! :)

I wish I could tell you exactly what I'm looking for using the technical jargon. This is what I would like to be able to do in .NET:
https://bitsex.net/software/2017/coap-endpoints-on-ikea-tradfri/

**Comment by WoodsterDK** [comment]
Hi there, sounds very promising.... no pressurebut any ETA?

**Comment by jimsch** [comment]
No later than the end of the month.

**Comment by WoodsterDK** [comment]
:+1:

**Comment by jimsch** [comment]
I have managed to get a first cut running.  I have not done all of the integration to get everything in one place and I have not really done adequate testing to think about doing a release, however if you are willing to clone and do your own builds you should be able to get started on doing this.  You will need both this repository and the COAP-Sandbox repository.   I think that the rest of the dependencies should be fine.

You can see in the example client directory what is needed to use a PSK for talking to a server.

**Comment by jimsch** [comment]
Go and grab drop 1.1.2 from nuget.  The example client program should have working code demonstrating how things work, but I have not yet run that code.  I have run parallel code.

**Comment by Moskus** [comment]
Fantastic! I'll give it a shot! 👍

**Comment by Moskus** [comment]
Once I figured out all the dependencies, it worked! Good job! All is well! :)

**Comment by jimsch** [comment]
Only client side is currently supported, server side will be coming in the future.

**Comment by Hydro8** [comment]
Do you have example to control Ikea Tradfri ? I need to achieve the same thing.

**Comment by Moskus** [comment]
Look here, that's where I started. :)
https://bitsex.net/software/2017/coap-endpoints-on-ikea-tradfri/

**Comment by jimsch** [comment]
While I have a Tradfi in the house, I have not really worked on trying to do much more than make sure that I can talk to it at this point.  I might start playing with it more later.

The example client program can be used to talk to it with the following command line

ExampleClient -psk=<your key here> GET coaps://ikea-tradfri/.well-known/core
