### ISSUE TITLE
Logging using FormatMessageHandler not working properly

### ISSUE THREAD

**Issue by lorenh** [jimsch/CoAP-CSharp#30]
When using the fancy lambda type of logging
   _Log.Debug(m => m("BeginReceive:  _running={0}", _running));

It renders this:
   "System.Action`1[Com.AugustCellars.CoAP.Log.FormatMessageHandler]"

**Comment by jimsch** [comment]
You are going to need to wait until the next version of the libraries to get this to work.

**Comment by lorenh** [comment]
You of course know the next question :-)   When might that be?

**Comment by jimsch** [comment]
With luck I should have an update out by the end of the week.  I think I have solved my update problems with the COSE library which means I should be able to figure out things here as well.

**Comment by jimsch** [comment]
Fixed
