### ISSUE TITLE
Ikea control group

### ISSUE THREAD

**Issue by Hydro8** [jimsch/CoAP-CSharp#31]
Hi
I didn't achieve to control a group from my Ikea gateway.

I tried to send { "3311":[{ "5851":0}]} or { "3311":[{ "5850":0}]} but it didn't work. 

Have you some  advices to get this work ?

Thank !

**Comment by jimsch** [comment]
What you should do is a get on the group.  You then should figure out what the group parameter is that you want to change and modify just that parameter at the group level and not at the bulb level.

**Comment by Hydro8** [comment]
When I query a group with :

client.Uri = new Uri("coaps://192.168.1.128:5684/15004/" + number);
Response response = client.Get();

I only get list of group's bulbs, no status for the entire group. Is it normal ?

**Comment by jimsch** [comment]
No that would be completely unexpected.  For one thing I would expect to see a group name as one o the parameters.  

You should have something like
/15004/139121

{"9001":"TRADFRI group","9039":203361,"9002":1490983341,"9003":139121,"5850":0,"5851":0,"9018":{"15002":{"9003":[65536,65537,65538]}}}

**Comment by Hydro8** [comment]
This is my response from her group :
 {"9001":"Salon","9002":1497335954,"9003":136834,"5850":1,"9039":217609,"5851":0,"9018":{"15002":{"9003":[65536,65537,65539,65542,65543]}}}

It looks like you, but how to know the group power / dimmer / color ?

**Comment by jimsch** [comment]
"9001":"Salon","9002":1497335954,"9003":136834,"5850":1,"9039":217609,"5851":0,"
                                                                        power   ^                          dimmer ^

**Comment by jimsch** [comment]
It did not display with non-breaking spaces - - the 5850 is power and 5851 is dimmer

**Comment by Hydro8** [comment]
It work ok for power but 5851 not change for dimmer level. It seems to not change for color too. 
And when I change only one bulb of the group, I still must loop through bulbs.

How do you use group/bulb state ? I query each bulb of the group to know state and if it's the same, I apply this state to the group. 

Anyway thank for your work, I know is related to Ikea API.

**Comment by Hydro8** [comment]
I tried to send directly { "5851":0} to my group id, don't work :/

**Comment by jimsch** [comment]
All I can say i that
           client.Uri = new Uri($"coaps://{Server}");
            client.UriPath = "/15004/166412";
            client.Get();
            Response rep = client.Put("{ \"5850\":0}");
            Thread.Sleep(3000);

works just fine for me.

**Comment by Hydro8** [comment]
With your code it work well for power and dimmer level !

Do you know how to change color ? I try 

`Response rep = client.Put("{ \"5850\":1,\"5707\":0,\"5708\":0,\"5709\":24930,\"5710\":24694,\"5711\":250,\"5706\":\"f5faf6\",\"9003\":0 }");`

But it doesn't work and I don't see color indication in group data.

**Comment by jimsch** [comment]
Given there is no color indicator in the group, I don't think you can.
