### ISSUE TITLE
Observer turns into polling

### ISSUE THREAD

**Issue by jimsch** [jimsch/CoAP-CSharp#6]
Following the guidance of the last paragraph of section 3.3.1, if an observation is setup and it goes stale, the code currently assumes that it has lost the observer at the server and attempts to re-create the same relationship with the same token.  While this is a good idea in concept, the fact that it is done w/o any input from the end-user is a problem.

The current code does the refresh after Max-Age plus a constant number of sections taken from the configuration (defaults to 2).  This means that it will occur every 62 seconds by default.

The following changes are needed:

1.  A way for the client to either opt-in or opt-out of the behavior
2.  A limit on the number of retries to be done before giving up.
3.  A better randomization on the back-off rate rather than use a constant from the configuration.

**Comment by dominionish** [comment]
Yes, this is exactly what happen. But can we ignore MaxAge and get observer data from server unlimit time, while observer not cancel? As I know client shouldnt recreate relationship with server. This should do border router or server. On some time server send ack and if it success recourse saved othervise resource canceled.

**Comment by dominionish** [comment]
As example you can see Copper (extention for Mozilla for working with coap). It work perfect. And always get observer data even if server unaccessable a couple hourds. Unfortunally it's just javaScript extention, but not C# dll)) Anyway thank you for your work. Hope you will solve all this problems. I can test your code on my coap devices

**Comment by jimsch** [comment]
This is now turned off by default

**Comment by dominionish** [comment]
Yes, I checked this version. And found something:
1. _message.FireRetransmitting(); on ReliabilityLayer still calls, so after 5 calls timeoutError occured. So I change code and it fixed:
...............
                else if (failedCount <= (_message.MaxRetransmit != 0 ? _message.MaxRetransmit : _config.MaxRetransmit) && (_message.Observe!=0 || _exchange.Request.ObserveReconnect))
                {
                    if (log.IsDebugEnabled)
                        log.Debug("Timeout: retransmit message, failed: " + failedCount + ", message: " + _message);

                    _message.FireRetransmitting();

                    // message might have canceled
                    if (!_message.IsCancelled)
                        _retransmit(this);
                }
                else if (_message.Observe != 0 || (_message.Observe == 0 && failedCount > (_message.MaxRetransmit != 0 ? _message.MaxRetransmit : _config.MaxRetransmit) || _exchange.Request.ObserveReconnect))
                {
                    if (log.IsDebugEnabled)
                        log.Debug("Timeout: retransmission limit reached, exchange failed, message: " + _message);
                    _exchange.TimedOut = true;
                    _message.IsTimedOut = true;
                    _exchange.Remove(TransmissionContextKey);
                    Cancel();
                }
...............
So FireRetransmitting doesnt call if message observable. But if _exchange.Request.ObserveReconnect = true it become callable.
2. After changing on 1 point i found new bug:
If server not available and we trying to observe resource, observer callback will never occured, because timer calls only 1 time, so on ReliabilityLayer on TransmissionContext constructor i changed code:
                if (_message.Observe==0)
                    _timer.AutoReset = true;
                else _timer.AutoReset = false;
3. And the last: I observer resourse. Then server become sleep. There is no polling, as you fixed it, and  after 60 sec (Max-Age) there is no timeout, as you fixed, but when server wake up and send observer update - data doesnt not come.
If server wakes up just in 1-60 secunds - all is ok - observer data comes, but if wakes up in 61 - more seconds - observer data doesn't come. It seems there is some more logic about Max-Age. May be after Max-Age seconds UDP closed? I didnt find something like this, but the problem exists

**Comment by dominionish** [comment]
1 problem with timeout fixed after I builded project using C# 7.0 Compiler.
But the problem with no observer data didnt solved

**Comment by jimsch** [comment]
Lets start with the basics.  The first set of code you modified deals with the fact that UDP is not a reliable transport.  This means that if one sends a UDP message it may not get delivered.  The code allows for a small set of pre-configured retries in this case.  This needs to happen independently if it being an observer request or a normal request.

The problem with trying to make sure that a confirmable message is delivered to a device which might currently be asleep is that if the device either is not there or never wakes up then you are using a fair amount of network traffic until such a time as the program would be killed. 

There is an easier way to get the "I do not want to re-try" by using the MessageType.Non value.  This can be set either in the constructor or by setting Request.Type.  Doing this says that I don't care about making sure the message gets delivered to the destination.

You should write code in the application to deal with a device you want to talk to and it may not be awake at any given time.  Although it is generally better to put some type of proxy agent closer to the device which does this if you need to talk to it from multiple devices.

I would suggest doing code in the application along the lines of

BEGIN CODE

Request request = new Request(Method.GET) {
  URI = new URI(....)
};
request.MarkObserve();

Response response = null;

while (response == null) {
   response = request.WaitForResponse(1000*60);   // Wait sixty seconds or a response;
};
Console.WriteLine(Utils.ToString(response)); /// Print so that we can look at it.

if (!response.HasOption(OptionType.Observe)) Console.WriteLine("Did not get an observe response!");

END CODE

While the device is asleep, it would send the message 5 times every minute until it gets a response.

One thing to remember is that if you go through a router to talk to the device, the routing may get dropped at some point if insufficient traffic goes through it.

**Comment by jgmdavies** [comment]
Hi Jim,

 

Couldn’t it be in that while loop forever, if there’s no response?

 

                Thanks,

                Jim

**Comment by jimsch** [comment]
Yes - this could be in an infinite loop, but that was going to be true for what he was doing to.  The assumption however is that either the app can be killed or the device really comes alive at some point.  It would be good to put an exit if it goes too long

**Comment by jgmdavies** [comment]
Ah, thanks Jim.  So it’s the same as having just one call (not in a loop), with an infinite timeout?

**Comment by jimsch** [comment]
No, this is not quite the same as having a single call with an infinite timeout.  It will produce more network traffic as it will send out a burst of UDP messages every minute.  The single call will produce only  a single burst of UDP messages.

**Comment by jgmdavies** [comment]
Of course, silly me!

 

I suppose the behaviour could be built into ‘WaitForResponse’, with an extra parameter or two, but this pattern is more open and controllable.

 

Many thanks for all your work on CoAP-CSharp – I’m looking forward to getting to grips with it.

 

Is this the best forum, and is there a working COAP test server around at the moment please?

 

                Many thanks,

                Jim

**Comment by jimsch** [comment]
There is a test server as part of the project, it does not get distributed via nuget but you can build it and play.  You can also look at the website http://coap.me/ which has a pointer to server and client resources that you can look at.  Additionally, there is always the JAVA version on github called californium.  I will however respond to things here as best I can as well.

**Comment by dominionish** [comment]
Hello, Jim!
Thank you for you answer!
1. About proxy agent you absolutely right. We are going to  place it near sensortag (server - device, wich sleep 60 minutes and not sleep only 20 seconds) and it (proxy) will be online always. But now we need to implement solution without proxy agent.
2. About "routing may get dropped at some point if insufficient traffic goes through it" you right too. We use OS Contiki and it can enable probing. This mean that it talk to border router periodically and so routing may not get dropped. This is not problem in our case.
3. About request.WaitForResponse.
Now to get data from Sensortag I use 
`request.Respond += (s, e) => myMethod(s, e);`
So what the principal difference? Can I manage to use timeout in this case like 
`request.WaitForResponse(1000*60);`? Or how can I use request.Respond to get data always without polling even if sensortag sleep long time.
4. About basics. I didnt get it at all. So can you explain me please it in my example:
I manage sensortag to sleep 60 seconds and not sleep 15 seconds. I started my client application, using your coap repository, and started wireshark(application to see all trafic like sniffer. Here  I can see if something come from sensortag to my computer). SO I observer to one resourse and every 60 seconds a message come from sensortag to my application client to myMethod function. And i can see this traffic in wireshark:
![image](https://cloud.githubusercontent.com/assets/8955774/26596375/f18bcff2-4587-11e7-810a-cea83bf5515c.png)
This is ideal situation. I need the same behavior when sensortag sleep more than 60 seconds. So lets try to sleep 120 seconds and see what will happen:
![image](https://cloud.githubusercontent.com/assets/8955774/26597110/4b90190c-458a-11e7-8f5c-9160241073d0.png)
As you can see there is a trafic from sensortag to my computer on the right hand of screenshot (Wireshark). But there is no message came to my application to myMethod function.
Why exactly this happen? Something like timeout happen? How can I know when this timeout occured and how can I restore connection? Using _retransmit? If yes, how can I do it?
And as the example I want to show you Copper. The same situation but instead my application I use Coap client Copper(Firefox extention):
Sleep - 120 seconds, not sleep -15 seconds:
![image](https://cloud.githubusercontent.com/assets/8955774/26597730/631aa2f2-458c-11e7-9205-bdff958e243c.png)
As you can see the same trafic in wireshark, but data came to Copper client (double data in wireshark because first - to application, second - to Copper)
How do you think what the reason can be?

**Comment by jimsch** [comment]
Lots of good information -thanks.  Can you capture console output or have you ever used the fancier Common.Logging captures - specifically NLog?  I want to see if I can get a capture of the internal logging information for this.

**Comment by jimsch** [comment]
Are you placing the request object into a global memory location or is it a local that goes out of scope?

**Comment by dominionish** [comment]
I had enabled log on another repository, but I forgot enable it using yours. I'll repeat all this actions, but with enabled log in 7-8 hours and will post here

**Comment by dominionish** [comment]
I save request object into a global memory location to have o posibility to cancel Observer when I need it.

**Comment by dominionish** [comment]
![image](https://cloud.githubusercontent.com/assets/8955774/26642496/5ee3ca0e-4647-11e7-93b3-8f072c022b40.png)
[SensorUI.txt](https://github.com/jimsch/CoAP-CSharp/files/1042232/SensorUI.txt)
At 2017-05-31 21:20:44.760133 message didnt come to SensorUI application as you can see on screenshot. Hope this log will help you

**Comment by jimsch** [comment]
It looks like the file got truncated and there is no request w/ an observe

**Comment by dominionish** [comment]
Hm... And there is no time in log. How can I swith on full log?

**Comment by jimsch** [comment]
What are you using for logging - just the default console logging or one of the common.logging modules?  It is going to very depending on what is being used.

**Comment by jimsch** [comment]
I am not really worried about times, but the following might help - it has a date format in the layout.

<nlog autoReload="true" throwExceptions="true">
 <targets>
   <target name="common.logging" type="Common.Logging.NLog.CommonLoggingTarget, Common.Logging.NLog10" layout="${longdate}|${level:uppercase=true}|${message}" filename="C:\temp\${date:format=yyyy-MM-dd}_logA.txt"/>
 </targets>
 <rules>
   <logger name="*" minlevel="Info" writeTo="common.logging"/>
 </rules>
</nlog>

**Comment by dominionish** [comment]
![image](https://cloud.githubusercontent.com/assets/8955774/26666915/f47958a8-46bb-11e7-8302-9b0a923ca02d.png)
[logUI.txt](https://github.com/jimsch/CoAP-CSharp/files/1043817/logUI.txt)
Hope now it full

**Comment by jimsch** [comment]
The good news is that I have figured out a lot of places where the problem isn't.  This means that things have narrowed down.  I should be releasing an update in the next day or two with additional tracing in new places to see if I can narrow the problem down farther.  I think it may be a restart issue that I fixed in a different place.

**Comment by dominionish** [comment]
Ok, realy good news. Tell me when you will push changes, I will give you new log.

**Comment by jimsch** [comment]
Ok - 1.1.4 is now pushed out

**Comment by dominionish** [comment]
![image](https://cloud.githubusercontent.com/assets/8955774/26793942/41e87f12-4a39-11e7-84cd-9b779c081f46.png)
[logUI.txt](https://github.com/jimsch/CoAP-CSharp/files/1052612/logUI.txt)
Hello! Here are logs information

**Comment by jimsch** [comment]
I really cannot see how it can possibly be failing at this point.
Basically, I am not seeing a UDP message being received.   Three possibilities - no message to receive, message is not being read by me, message is getting lost between hardware and my program.  I cannot see how to deal with the last.

* I have checked in a lot of debug statements dealing with the UDP channel that I will need to remove essentially, but it will track almost every function call. 
* Please double check that the port numbers are still correct. (Yes I am sure that you have already done this)

Are you using 4.5 or 4.0 for the framework?  What OS are you running on?

**Comment by dominionish** [comment]
Good day!
About port number I didnt check. You think that it could be changed by sensortag? I'll check this.
I use CoAP.NET40 project, so I use framework 4.0. OS Windows 7 Maximum.
The fact is - Copper work and receive message. I'll check it again today and will receive you a sceenshot. Ma y be Copper get messages from any ports, even if it changes - I dont know. I will send you sensortag log too.
May be UDPConnection has something like timeout = 60 secs. And if you will not recheck it - it will close.

**Comment by dominionish** [comment]
![image](https://cloud.githubusercontent.com/assets/8955774/26820124/29c79f58-4abb-11e7-90f8-72a014d1b79a.png)
[logUI.txt](https://github.com/jimsch/CoAP-CSharp/files/1054237/logUI.txt)

[putty.txt](https://github.com/jimsch/CoAP-CSharp/files/1054239/putty.txt)

Port didnt changed during observer period. Copper working, UI - dont. All logs include sensortag log included.
The only help i can get you is get you remote access to my computer by TeamViewer if you need debug online

**Comment by jimsch** [comment]
Yeah, I didn't really think it was a port problem, but I am starting to grasp at straws.

* It does not look like you pulled down the updates in the project which added some additional logging.  At least I do not see them in the file you posted.
* I would like you to try using the example client program in addition to yours to try and observe the resource.  I think the command line would be "CoAPClient -e OBSERVE coap://sensortag/rest/commonImp"  This should eliminate your program from the equation and make it just my code.   The -e option uses the callback function, a -l option would loop.

I have used this to observe a resource that fires an event every 3 minutes without any problems. I don't know if I want it to succeed or fail.

**Comment by dominionish** [comment]
Hello! Sory for long waiting!
I checked your examples in branch master and here are results:
1. CoAPClient -e OBSERVE coap://[fd00::212:4b00:c4a:5c80]:5683/rest/counter/total - dont work at all. No one message come. I dont know why:
![image](https://user-images.githubusercontent.com/8955774/27027220-f55b7884-4f79-11e7-9127-20d2a64439a5.png)
2. CoAPClient -l OBSERVE coap://[fd00::212:4b00:c4a:5c80]:5683/rest/counter/total work, but only if sensortg sleep less than 60 sec. If it sleem more than 60 seconds, message doesnt come as before. So the same problem in you client example
![image](https://user-images.githubusercontent.com/8955774/27028108-3a334902-4f7d-11e7-8f8d-bec0914f4cfc.png)

And one more.
I enable polling to make my application work. And observe on 2 resourse. Sensortag sleeps 1 hour, then notSleep 30 seconds. In this case messages came and all worked about 6 hours, then messages didnt come and in log i found this:
Timeout: message already acknowledged, cancel retransmission of CON-GET ID=22551, Token=44FDC510, Options=[URI-Path=rest, counter, total, Observe=0], [no payload]
What does it mean? Why new ack message stops retransmission?
Here is full log:
[logUI.txt.2017-06-09(important).txt](https://github.com/jimsch/CoAP-CSharp/files/1067707/logUI.txt.2017-06-09.important.txt)

**Comment by jimsch** [comment]
Just to double check - are you using a build version or a nuget version of the library?  I am still not seeing some logging that I expect to see.

The message you are worried about is expected.  If I send a message and one gets back an ACK on for it.  Then it will not be re-transmitted - that is what this is saying.  I haven't looked yet hard enough to see which message it is being done for.

**Comment by dominionish** [comment]
I cloned the last version from you repository from master branch, built it and ran.

And check please how to make observer go on even after this message (ACK)

**Comment by jimsch** [comment]
If you look at the file UDPChannel.NET40.cs on line 28, there should be log message.  Please make sure that it is enabled and logging so that I can see what is happening in the UDP code itself.

**Comment by dominionish** [comment]
![image](https://user-images.githubusercontent.com/8955774/27100044-38792bf8-5096-11e7-88d4-64fb19950a17.png)
Where did you implement LOG_UDP_CHANNEL?  I didnt find any implementation
_Log variable was not implemented, so if you'll delete #if LOG_UDP_CHANNEL and #endif, There will be error:
![image](https://user-images.githubusercontent.com/8955774/27100177-9e3c9380-5096-11e7-9743-b3e678cd2d56.png)
May be I dont understand something

**Comment by jimsch** [comment]
You will find the _Log in  UDPSocket - these two files together implement the class.  The define should be on for debug compiles.

**Comment by jimsch** [comment]
I got it to reproduce - and we have a winner.  Now to figure out how to get around the winner.

The firewall is blocking the messages from being delivered to the application.  This is why it worked just fine for me because I was running the server and client on the same machine so the firewall did not come into effect.  My timeout seems to be around 4 minutes rather than your really short one.  If you can see if disabling your client firewall fixes the problem

**Comment by jimsch** [comment]
Ok - I have done several things that validate that problem appears to be the firewall.  It appears that the timeout period on windows is highly dependent on both the OS and hardware but starts in as little as 64 seconds (See https://stackoverflow.com/questions/14856639/udp-hole-punching-timeout for a way to look for the value.)  This value is hard coded into the OS and cannot be changed programmatically or by a configuration change to the best of my knowledge.  In essence there is a router sitting on the edge of the machine to help mess things up.

The ways that I have found to work around this:
1.  Have the program send a lot of messages to the destination to keep the route open.  This is not really a good idea.
2.  Open an inbound port in the firewall and change the client program to always use that port when it executes.  I have verified that this works on my machine.   The port can either be configured as opened either by manual configuration or programmatically.  In either event there is a requirement for administrative privileged.  At this point I do not believe that it would make sense to provide a function in the CoAP library to perform this operation, but I could be convinced.

**Comment by dominionish** [comment]
Yes, you right. The problem was in the firewall.
I test some issue and one issue solved my problem. I did this:
![image](https://user-images.githubusercontent.com/8955774/27168263-5698737c-51be-11e7-903c-1ff83c0abac5.png)
So when you set port number in this case on start application firewall ask you whould you loke to get access to this application. You click yes button and all will work. But when you use port 0 - UDPConnection choose it by itselph and there is no firewall message about access.
So as variant can you please create Config parameter like "port" and use this parameter as in screenshot above. And When user didnt set this port only in this case use port 0. So we will be able to choose static port as we wish.
I'll test this solution a week may be it has some problems. I'll let you know

**Comment by jimsch** [comment]
There is an example of creating and defining and endpoint in the example code for dealing with coaps already.

The code for you looks like below where you create a specific endpoint and then set the endpoint on the request.

           CoAPEndPoint ep = null;
                ep = new CoAPEndPoint(40001);
                ep.Start();
                request.EndPoint = ep;

            request.URI = uri;

**Comment by dominionish** [comment]
Cool! I didnt know. Thank you!

**Comment by dominionish** [comment]
And I found another problem.
1. I started sensortag
2. Make Get request - all is fine. I receive response
3. I switch off sensortag or make him sleeping
4. Make Get request - nothing happen and in some seconds unlimit polling come!
As the result a get unlimit timeout errors:
![image](https://user-images.githubusercontent.com/8955774/27174801-c2e9f1d2-51d6-11e7-84bd-7271e7512973.png)

**Comment by jimsch** [comment]
It would be easier for me if you attached the wireshark log rather than the picture so that I can look at all of the messages and see what is tied to what  My first guess is going to be that the freshness code got turned back on but I am not sure that the timeouts look correct for that.

**Comment by dominionish** [comment]
Ok, got it. I'll give you log in 3 days

**Comment by dominionish** [comment]
Here is all kind of logs from wireshark: I didnt know what format do you need so i create 3 different logs:
https://drive.google.com/file/d/0B322t_kof_jkUGc3UkhUMzJyOEE/view?usp=sharing

**Comment by dominionish** [comment]
Sory, it's my fault. Bug was in my code. All is working fine!

**Comment by jimsch** [comment]
I think this  is all fixed
