### ISSUE TITLE
Logging to console...

### ISSUE THREAD

**Issue by Moskus** [jimsch/CoAP-CSharp#7]
Okay, I'm an amature and it shows. I apologize!
But how do I disable the debug and info logging that is written to the console?

**Comment by jimsch** [comment]
The logging system is kinda crazy, so the fact that you don't understand it is totally understandable.  I don't think that I have all of it down yet.

Put this in the beginning of your program.

            Com.AugustCellars.CoAP.Log.LogManager.Level = LogLevel.None;

**Comment by Moskus** [comment]
I could have sworn that I tried that I tried that.... oh well, it works now! Thank you very much!

(My (at the moment) little program is noticeably faster).

**Comment by jimsch** [comment]
This is now turned off by default
